Hahaha

diff --git a/tivotranscode b/tivotranscode
--- a/tivotranscode
+++ b/tivotranscode
@@ -21,11 +21,7 @@ TIVO=""
 MAK=""
 VERBOSE=0
 
-# Current date/time
-DATE=`date +%Y%m%d%H%M`
-GETSCRIPT="./get_$DATE.sh"
-
-# Determine getopt support...
+# Determine getopt support, and parse all the parameters we need.
 getopt -T
 if [[ $? -eq 4 ]]; then
 	set -- $(getopt -o "hfs:t:m:v" -l "help,first-run,show-list:,tivo:,media-key:,verbose" -- "$@")
@@ -92,100 +88,144 @@ if [[ "$FIRSTRUN" == "1" ]]; then
 	fi
 fi
 
+# TODO: Make sure HandbrakeCli and tivodecode are on the command line.
+
+# getShowList(outputfilename)
+# Parses the global NOWPLAYING list and writes all the show titles (individual and folders)
+# Which are not special 'HD' or 'TiVo Suggestions' to tthe given file. You can 
+# use this to get a list of all the shows on the tivo, and then only select the 
+# ones you want to process each run.
+function getShowList {
+	local output="$1"
+	
+	# Get the list of folders from the NOWPLAYING output, parsing out the URLs to get the episode lists.
+	echo $NOWPLAYING | xsltproc lib/listfolders.xsl - | sed 's/|.*//g' > $output
+
+	# Get the list of individual shows from the NOWPLAYING, append to output.
+	echo $NOWPLAYING | xsltproc lib/listshows.xsl - >> $output
+}
+
+# Construct the global SUBSCRIBED array, and a function to load it.
+SUBSCRIBED=()
+function loadSubscribed {
+	while read TITLE; do
+		SUBSCRIBED+=("${TITLE}")
+	done < $SHOWLIST
+}
+
+# Construct the global LOCKNAME, and a function to get it, or kill the process.
+LOCKNAME="encode_$TIVO.lock"
+function lockOrDie {
+	lockfile -10 -r 3 $LOCKNAME
+	if [[ "$?" != "0" ]]; then
+		echo "Could not obtain lock to process shows for TiVo $TIVO. Perhaps another process is still running?"
+		exit 1
+	fi
+}
+
+# Removes the lock file.
+function cleanupLock {
+	rm -f $LOCKNAME
+}
+
+# isProcessed(showname, programid)
+# returns 0 if the show has never been processed, false otherwise.
+function isNotProcessed {
+	PROCESSED=`fgrep "$1:$2" $PROCESSEDLIST`
+	# return values in bash are so silly.
+	if [[ "$PROCESSED" == "" ]]; then
+		return 0
+	else
+		return 1
+	fi
+}
+
+# processShow(nowplayingxml, showname)
+# Parses the provided nowplaying xml (can be global or show-specific) for programids matching the given show name
+# Downloads & decodes the mpeg streams from the tivo.
+function processShow {
+	local PROGRAMIDS
+	PROGRAMIDS=`echo $1 | xsltproc --stringparam ShowTitle "$2" lib/programid.xsl - `
+	for PROGRAMID in $PROGRAMIDS; do
+		if isNotProcessed $2 $PROGRAMID; then
+			echo "Processing $2:$PROGRAMID" 1>&2
+			
+			# Parse the URL from the now playing.
+			local MPEGURL
+			MPEGURL=`echo $1 | xsltproc --stringparam ProgramId "$PROGRAMID" lib/mpegurl.xsl -`
+			
+			local TARGETFILENAME
+			TARGETFILENAME=`echo $1 | xsltproc --stringparam ProgramId "$PROGRAMID" lib/targetfilename.xsl -`
+			
+			echo "  Craeting output diretory..."
+			mkdir -p "$2"
+
+			echo "  Downloading & Decoding from $MPEGURL"
+			curl --cookie sid=abc -s --digest -k -u tivo:$MAK -c cookies.txt "$MPEGURL" | tivodecode -m $MAK -o $PROGRAMID.tivo -
+			
+			echo "  Transcoding... to $TARGETFILENAME"
+			HandBrakeCLI -i $PROGRAMID.tivo -o $TARGETFILENAME -f mp4 -O -e x264 --x264-profile high -b 1100 --two-pass -r 29.97 -a 1 -E faac -B 160 -6 stereo -R Auto --gain 5.0 --detelecine --decomb --strict-anamorphic
+
+			echo "$2:$PROGRAMID" >> $PROCESSEDLIST
+		else
+			echo "Skipping $2:$PROGRAMID. This episode has already been processed. Please remove it from your TiVo." 1>&2
+		fi
+	done
+	
+	if [[ "$PROGRAMIDS" == " " ]]; then
+		# Found nothing
+		return 0
+	else
+		# Found something
+		return 1
+	fi
+}
+
+# Function which loads the subscriptions into the global array, then takes action
+# on each show in the array, looking for episodes on the TiVo to process.
+function processSubscriptions {
+	loadSubscribed
+	
+	# For every showname we're subscribed to, look for a ProgramID with that show title from the global Now Playing list.
+	for SHOW in "${SUBSCRIBED[@]}"; do
+		# processShow returns true if we didn't find anything.
+		if processShow "$NOWPLAYING" "$SHOW"; then
+			local TITLEPLAYINGURL
+			TITLEPLAYINGURL=`echo $NOWPLAYING | xsltproc lib/listfolders.xsl - | grep "$SHOW" | sed 's/.*|//g'`
+			echo "Getting the Now Playing list for episodes of $SHOW from $TITLEPLAYINGURL"
+
+			local TITLEPLAYING
+			TITLEPLAYING="`curl -s --digest -k -u tivo:$MAK "$TITLEPLAYINGURL"`"
+			
+			if processShow "$TITLEPLAYING" "$SHOW"; then
+				echo "Did not find any pending episodes on the TiVo for $SHOW"
+			fi
+		fi
+	done
+}
+
+# Get a global NowPlaying list (of individual shows and folders)
+# We recurse into folders manually when we need to, so that we can get the full
+# listing of -all- the shows (and episodes if necessary)
+echo "Connecting as tivo@$TIVO to download Now Playing list...."
+NOWPLAYING="`curl -s --digest -k -u tivo:$MAK "https://$TIVO/TiVoConnect?Command=QueryContainer&Container=%2FNowPlaying"`"
+
+# If this is a first run, we are going to save data.
 if [[ "$FIRSTRUN" == "1" ]]; then
 	echo "$TIVO" > ~/.tvt-host
 	echo "$MAK" > ~/.tvt-mak
+	getShowList $SHOWLIST
 else
 	if [[ ! -f $SHOWLIST ]]; then
 		echo "Could not read from specified show list file: $SHOWLIST" 1>&2
 		exit 1
 	fi
+
+	# Make sure we have a file to keep a list of all the things we've already processed.
+	touch $PROCESSEDLIST
+	
+	lockOrDie
+	processSubscriptions
+	cleanupLock
 fi
-
-echo "Connecting as tivo@$TIVO to download Now Playing list...."
-NOWPLAYING="`curl -s --digest -k -u tivo:$MAK "https://$TIVO/TiVoConnect?Command=QueryContainer&Container=%2FNowPlaying"`"
-echo "Got it"
-
-if [[ "$FIRSTRUN" == "1" ]]; then
-	# Contact the TiVo at the given address, parse it's now playing for a list of shows.
-	# We're going to write all the show names to the file. You can edit it when we're done.
-
-	# Get the list of folders from the NOWPLAYING output, parsing out the URLs to get the episode lists.
-	echo $NOWPLAYING | xsltproc lib/listfolders.xsl - | sed 's/|.*//g' > $SHOWLIST
-
-	# Get the list of individual shows from the NOWPLAYING output.
-	echo $NOWPLAYING | xsltproc lib/listshows.xsl - >> $SHOWLIST
-else
-	# Time to make the donuts!
-	# ------------------------
-	# Try to get a lockfile. If we can't get it, assume the lock is taken, and don't do anything. 
-	# This lets us schedule the job on a regular interval and have it not interfere with itself.
-	LOCKNAME="encode_$TIVO.lock"
-	lockfile -10 -r 3 $LOCKNAME
-	if [[ "$?" == "0" ]]; then
-
-		# Clean up from the last run.
-		echo "#!/bin/bash" > $GETSCRIPT
-
-		# Make sure we have a file to keep a list of all the things we've already included.
-		touch $PROCESSEDLIST
-
-		# Read the list of shows from the input stream.
-		SUBSCRIBED=()
-		while read TITLE; do
-			SUBSCRIBED+=("${TITLE}")
-		done < $SHOWLIST
-
-
-
-		for TITLE in "${SUBSCRIBED[@]}"; do
-			echo "Looking for individual episodes of $TITLE"
-
-			PROGRAMS=`echo $NOWPLAYING | xsltproc --stringparam ShowTitle "$TITLE" lib/programid.xsl - `
-			for PROGRAMID in $PROGRAMS; do
-				PROCESSED=`fgrep "$TITLE:$PROGRAMID" $PROCESSEDLIST`
-				if [[ "$PROCESSED" == "" ]]; then
-					echo "Including $TITLE:$PROGRAMID" 1>&2
-					echo $NOWPLAYING | xsltproc --stringparam ShowTitle "$TITLE" --stringparam MAK "$MAK" --stringparam ProgramId "$PROGRAMID" --stringparam PROCESSEDLIST "$PROCESSEDLIST" lib/encodeshow.xsl - >> $GETSCRIPT
-				else
-					echo "Skipping $TITLE:$PROGRAMID. This episode has already been processed." 1>&2
-				fi
-			done
-
-			if [[ "$PROGRAMS" == " " ]]; then
-				TITLEPLAYINGURL=`echo $NOWPLAYING | xsltproc lib/listfolders.xsl - | grep "$TITLE" | sed 's/.*|//g'`
-				echo "Getting the Now Playing list for episodes of $TITLE from $TITLEPLAYINGURL"
-
-				TITLEPLAYING="`curl -s --digest -k -u tivo:$MAK "$TITLEPLAYINGURL"`"
-
-
-				PROGRAMS=`echo $TITLEPLAYING | xsltproc --stringparam ShowTitle "$TITLE" lib/programid.xsl - `
-				for PROGRAMID in $PROGRAMS; do
-					PROCESSED=`fgrep "$TITLE:$PROGRAMID" $PROCESSEDLIST`
-					if [[ "$PROCESSED" == "" ]]; then
-						echo "Including $TITLE:$PROGRAMID" 1>&2
-						echo $TITLEPLAYING | xsltproc --stringparam ShowTitle "$TITLE" --stringparam MAK "$MAK" --stringparam ProgramId "$PROGRAMID" --stringparam PROCESSEDLIST "$PROCESSEDLIST" lib/encodeshow.xsl - >> $GETSCRIPT
-					else
-						echo "Skipping $TITLE:$PROGRAMID. This episode has already been processed." 1>&2
-					fi
-				done
-			fi
-		done
-
-
-
-
-		chmod +x $GETSCRIPT
-
-		# Execute the generated file!
-		$GETSCRIPT
-
-		echo "Cleaning up locks & generated script."
-		rm -f $LOCKNAME
-		rm $GETSCRIPT
-	else
-		echo "Could not obtain lock, prior execution must be running."
-	fi
-fi
-
 
